Migration and implementation interfaces
kaiyuanshe/OpenHackathon-service pull request #6
Opened 2024-08-13 08:12 UTC by luojiyin1987

2024-08-13 08:13 UTC, luojiyin1987 commented
@TechQuery   是声明类还是接口？

2024-08-13 09:59 UTC, TechQuery commented
> @TechQuery   是声明一个类还是一个接口？ 

必然是一个类啊，要不怎么用装饰器？

2024-08-15 14:51 UTC, luojiyin1987 commented
https://hackathon-api.kaiyuanshe.cn/swagger/index.html 
 如何实现 创建保存一个  award ？  对应接口   /v2/hackathon/{hackathonName}/award
如何验证身份？  解构获取请求的参数？     @TechQuery

2024-09-07 15:25 UTC, luojiyin1987 commented
@TechQuery  麻烦看一下代码。 好没底气，确认是否可以正常运行。

2024-09-07 16:53 UTC, TechQuery commented
> @TechQuery  麻烦看一下代码。 好没底气，确认是否可以正常运行。

那就本地运行一下看看啊

2024-09-09 13:52 UTC, luojiyin1987 commented
> > @TechQuery  麻烦看一下代码。 好没底气，确认是否可以正常运行。
> 
> 那就本地运行一下看看啊
这是服务端， 我怎么验证？   用swagger 验证？

2024-09-09 16:26 UTC, TechQuery commented
> 这是服务端， 我怎么验证？   用swagger 验证？ 

要么像我写单元测试一样 #18，用可编程的 HTTP 客户端调接口，要么就用 Swagger 或者 PostMan 这些图形客户端。

后端接口写好了给前端，前端也得这么验证。但如果你只交给前端验证，那就成了 FDBD（前端驱动后端开发），是找骂。

2024-12-13 19:14 UTC, TechQuery requested changes

2024-12-13 19:14 UTC, TechQuery commented on source/model/index.ts
> +export * from './Award';
除此之外，还要在下面注册。

2024-12-13 19:14 UTC, TechQuery commented on source/controller/Award.ts
> +        }
```suggestion
        awardData: Award
```
 `class` 才既有类型信息，又有运行时的实体，才能在服务器启动的时候生成 Swagger 文档。

2024-12-13 19:14 UTC, TechQuery commented on source/controller/Award.ts
> +        if (!hackathon) throw new NotFoundError('Hackathon not found');
```suggestion
        if (!hackathon) throw new NotFoundError(`Hackathon ${hackathon} is not found');
```

2024-12-13 19:14 UTC, TechQuery commented on source/controller/Award.ts
> +        return saved;
```suggestion
        const saved = this.store.save({
            ...awardData,
            hackathon
        });
        await ActivityLogController.logCreate(currentUser, 'Award', saved.id);

        return saved;
```

2024-12-13 19:14 UTC, TechQuery commented on source/controller/Award.ts
> +        return award;
用 `store.findOneBy()` 一条语句就可以解决。

2024-12-13 19:14 UTC, TechQuery commented on source/controller/Award.ts
> +        >
```suggestion
    @Put('/:awardId')
    @Authorized()
    @ResponseSchema(Award)
    async updateOne(
        @CurrentUser() currentUser: User,
        @Param('hackathonName') hackathonName: string,
        @Param('awardId') awardId: number,
        @Body()
        updateData: Award
```
为了复用创建时的 model，我们现在统一用**全量更新**来实现。

2024-12-13 19:14 UTC, TechQuery commented on source/controller/Award.ts
> +        const saved = await this.store.save(award);
用对象展开，直接一条语句搞定。

2024-12-13 19:55 UTC, TechQuery requested changes

2024-12-13 19:55 UTC, TechQuery commented on source/model/Award.ts
> +import { Base, Media } from './Base';
```suggestion
import { IsInt, IsOptional, IsString } from 'class-validator';

import { Base, Media } from './Base';
```

2024-12-13 19:55 UTC, TechQuery commented on source/model/Award.ts
> +    description: string;
```suggestion
    @IsOptional()
    @Column({ nullable: true })
    description?: string;
```

2024-12-13 19:55 UTC, TechQuery commented on source/model/Award.ts
> +    target: 'team' | 'individual';
声明 `enum AvwardTarget` 后：

```suggestion
    @IsEnum(AvwardTarget)
    @IsOptional()
    @Column({ type: 'simple-enum', enum: AwardTarget, nullable: true })
    target?: AwardTarget;
```

2024-12-13 19:55 UTC, TechQuery commented on source/model/Award.ts
> +    pictures: Media[];
```suggestion
    @IsObject({ each: true })
    @ValidateNested()
    @IsOptional()
    @Column({ type: 'simple-json', nullable: true })
    pictures?: Media[];
```

2024-12-13 19:55 UTC, TechQuery commented on source/model/Award.ts
> +}
没写授奖逻辑就先不要写数据结构，而且 `'assignmentId' | 'assigneeId' | 'awardId'` 是 TypeORM 在数据库自动生成的字段，不会反映在查出来的数据中。

2024-12-13 19:55 UTC, TechQuery commented on test/main.test.ts
> +            hackathon: expect.any(Object)
下面再加一个断言：`award.hackathon.id === testHackathon.id`

2024-12-13 19:55 UTC, TechQuery commented on test/main.test.ts
> +    let testAward: any;
```suggestion
    let testAward: Award;
```

2024-12-13 19:55 UTC, TechQuery commented on test/main.test.ts
> +                awardData
不断言数据变更，可以写个最简数据：

```suggestion
        try {
            await client.award.awardControllerCreateOne(
                testHackathon.name,
                { name: 'Unauthorized Award' }
```

2024-12-13 19:55 UTC, TechQuery commented on test/main.test.ts
> +            testHackathon.name,
前一个用例已经把 `testHackathon` 从数据库删了，你还咋测？应该把 `Award` 所有用例移到原倒数第二个用例之后。

2024-12-14 16:01 UTC, luojiyin1987 commented
还是没生成 swagger 对应的 award 接口， 也没生成对应的 client.ts。 @TechQuery

2024-12-14 16:05 UTC, TechQuery commented
> 还是没生成 swagger 对应的 award 接口， 也没生成对应的 client.ts。 @TechQuery 

因为没注册：https://github.com/kaiyuanshe/OpenHackathon-service/blob/e4cbafc08ccd9230dad7c6579286f13d8cd890e3/source/controller/index.ts#L39-L60

2024-12-14 16:20 UTC, luojiyin1987 commented
swagger 对应的 award 接口是生成了。 但是 `client.ts`  的 `award` 的定义没有 @TechQuery

2024-12-14 17:58 UTC, TechQuery commented
> swagger 对应的 award 接口是生成了。 但是 `client.ts` 的 `award` 的定义没有 @TechQuery

![image](https://github.com/user-attachments/assets/a304b01c-2a0b-426b-9924-3ec3a0b4bc21)

2024-12-15 15:29 UTC, TechQuery requested changes

2024-12-15 15:29 UTC, TechQuery commented on source/controller/index.ts
> +    AwardController
放到 `HackathonController` 上面，越具体的路由越要放在前面匹配。

2024-12-15 16:05 UTC, luojiyin1987 commented
https://github.com/kaiyuanshe/OpenHackathon-service/blob/bfc2f5da1035dc838b2048aca0e4a69d1928b132/test/main.test.ts#L351
 我还没解决 这个报错
Type 'import("/home/code/nodeWork/OpenHackathon-service/test/client").Award' is not assignable to type 'import("/home/code/nodeWork/OpenHackathon-service/source/model/Award").Award'.
  Property 'description' is optional in type 'Award' but required in type 'Award'

2024-12-15 16:13 UTC, TechQuery commented
>  https://github.com/kaiyuanshe/OpenHackathon-service/blob/bfc2f5da1035dc838b2048aca0e4a69d1928b132/test/main.test.ts#L351
>  我还没解决 这个报错
> Type 'import("/home/code/nodeWork/OpenHackathon-service/test/client").Award' is not assignable to type 'import("/home/code/nodeWork/OpenHackathon-service/source/model/Award").Award'.
>   Property 'description' is optional in type 'Award' but required in type 'Award'  

因为这条没改完，TS 类型和装饰器的语义要一致：https://github.com/kaiyuanshe/OpenHackathon-service/pull/6#discussion_r1884393926

2024-12-16 05:15 UTC, luojiyin1987 commented
https://github.com/kaiyuanshe/OpenHackathon-service/blob/31e646d35eccb0d8531c582b204a3494e5365379/test/main.test.ts#L351  
 报 
`Type 'import("/home/code/nodeWork/OpenHackathon-service/test/client").Award' is not assignable to type 'import("/home/code/nodeWork/OpenHackathon-service/source/model/Award").Award'.
  Types of property 'target' are incompatible.
    Type '"team" | "individual"' is not assignable to type 'AwardTarget'.
      Type '"team"' is not assignable to type 'AwardTarget'.ts(2322)`

2024-12-16 05:44 UTC, TechQuery commented
> https://github.com/kaiyuanshe/OpenHackathon-service/blob/31e646d35eccb0d8531c582b204a3494e5365379/test/main.test.ts#L351  
>  报 
> `Type 'import("/home/code/nodeWork/OpenHackathon-service/test/client").Award' is not assignable to type 'import("/home/code/nodeWork/OpenHackathon-service/source/model/Award").Award'.
>   Types of property 'target' are incompatible.
>     Type '"team" | "individual"' is not assignable to type 'AwardTarget'.
>       Type '"team"' is not assignable to type 'AwardTarget'.ts(2322)`

报错提示很清楚啊，两处同名类型的字段定义有差异。你用自动生成的 `client`，类型也应该用自动生成文件中的。

2024-12-16 07:50 UTC, luojiyin1987 commented
```
  ● Main business logic › should update an award

    thrown: Response {
      "data": null,
      "error": Object {
        "name": "NotFoundError",
        "stack": "Error

      57 |         });
      58 |         if (!staff)
    > 59 |             throw new routing_controllers_1.NotFoundError();
         |                   ^
      60 |         await Hackathon_1.HackathonController.ensureAdmin(updatedBy.id, name);
      61 |         const saved = await store.save({
      62 |             ...staff,
```
```
Main business logic › should delete an award

    thrown: Response {
      "data": null,
      "error": Object {
        "name": "NotFoundError",
        "stack": "Error

      73 |         });
      74 |         if (!staff)
    > 75 |             throw new routing_controllers_1.NotFoundError();
         |                   ^
      76 |         if (deletedBy.id === uid)
      77 |             throw new routing_controllers_1.ForbiddenError();
      78 |         await Hackathon_1.HackathonController.ensureAdmin(deletedBy.id, name);

```
是路由没注册成功 ？

2024-12-16 08:57 UTC, TechQuery commented
> ```
>   ● Main business logic › should update an award
> 
>     thrown: Response {
>       "data": null,
>       "error": Object {
>         "name": "NotFoundError",
>         "stack": "Error
> 
>       57 |         });
>       58 |         if (!staff)
>     > 59 |             throw new routing_controllers_1.NotFoundError();
>          |                   ^
>       60 |         await Hackathon_1.HackathonController.ensureAdmin(updatedBy.id, name);
>       61 |         const saved = await store.save({
>       62 |             ...staff,
> ```
> ```
> Main business logic › should delete an award
> 
>     thrown: Response {
>       "data": null,
>       "error": Object {
>         "name": "NotFoundError",
>         "stack": "Error
> 
>       73 |         });
>       74 |         if (!staff)
>     > 75 |             throw new routing_controllers_1.NotFoundError();
>          |                   ^
>       76 |         if (deletedBy.id === uid)
>       77 |             throw new routing_controllers_1.ForbiddenError();
>       78 |         await Hackathon_1.HackathonController.ensureAdmin(deletedBy.id, name);
> 
> ```
> 是路由没注册成功 ？ 

好奇怪啊，为什么你 `Award` 的测试却报错报在 `Staff`……

2024-12-16 09:50 UTC, TechQuery requested changes

2024-12-16 09:50 UTC, TechQuery commented on source/controller/Award.ts
> +        awardData: Award
```suggestion
        @Body() awardData: Award
```

2024-12-16 09:50 UTC, TechQuery commented on source/controller/Award.ts
> +    }
```suggestion
    getOne(@Param('awardId') id: number) {
        return this.store.findOneBy({ id });
    }
```

2024-12-16 09:50 UTC, TechQuery commented on source/model/Award.ts
> +    quantity?: number;
```suggestion
    @IsInt()
    @Min(0)
    @IsOptional()
    @Column({ nullable: true })
    quantity?: number;
```

2024-12-16 09:50 UTC, TechQuery commented on source/model/Award.ts
> +    pictures?: Media[];
```suggestion
    @Type(() => Media)
    @ValidateNested({ each: true })
    @IsOptional()
    @Column({ type: 'simple-json', nullable: true })
    pictures?: Media[];
```

2024-12-16 10:18 UTC, luojiyin1987 commented
> > ```
> >   ● Main business logic › should update an award
> > 
> >     thrown: Response {
> >       "data": null,
> >       "error": Object {
> >         "name": "NotFoundError",
> >         "stack": "Error
> > 
> >       57 |         });
> >       58 |         if (!staff)
> >     > 59 |             throw new routing_controllers_1.NotFoundError();
> >          |                   ^
> >       60 |         await Hackathon_1.HackathonController.ensureAdmin(updatedBy.id, name);
> >       61 |         const saved = await store.save({
> >       62 |             ...staff,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Main business logic › should delete an award
> > 
> >     thrown: Response {
> >       "data": null,
> >       "error": Object {
> >         "name": "NotFoundError",
> >         "stack": "Error
> > 
> >       73 |         });
> >       74 |         if (!staff)
> >     > 75 |             throw new routing_controllers_1.NotFoundError();
> >          |                   ^
> >       76 |         if (deletedBy.id === uid)
> >       77 |             throw new routing_controllers_1.ForbiddenError();
> >       78 |         await Hackathon_1.HackathonController.ensureAdmin(deletedBy.id, name);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 是路由没注册成功 ？
> 
> 好奇怪啊，为什么你 `Award` 的测试却报错报在 `Staff`……

我看了好久也没明白

2024-12-19 21:05 UTC, TechQuery commented
> > > ```
> > >   ● Main business logic › should update an award
> > > 
> > >     thrown: Response {
> > >       "data": null,
> > >       "error": Object {
> > >         "name": "NotFoundError",
> > >         "stack": "Error
> > > 
> > >       57 |         });
> > >       58 |         if (!staff)
> > >     > 59 |             throw new routing_controllers_1.NotFoundError();
> > >          |                   ^
> > >       60 |         await Hackathon_1.HackathonController.ensureAdmin(updatedBy.id, name);
> > >       61 |         const saved = await store.save({
> > >       62 |             ...staff,
> > > ```  
> > >   
> > > ```
> > > Main business logic › should delete an award
> > > 
> > >     thrown: Response {
> > >       "data": null,
> > >       "error": Object {
> > >         "name": "NotFoundError",
> > >         "stack": "Error
> > > 
> > >       73 |         });
> > >       74 |         if (!staff)
> > >     > 75 |             throw new routing_controllers_1.NotFoundError();
> > >          |                   ^
> > >       76 |         if (deletedBy.id === uid)
> > >       77 |             throw new routing_controllers_1.ForbiddenError();
> > >       78 |         await Hackathon_1.HackathonController.ensureAdmin(deletedBy.id, name);
> > > ```
> > >   
> > > 是路由没注册成功 ？
> > 
> > 好奇怪啊，为什么你 `Award` 的测试却报错报在 `Staff`……
> 
> 我看了好久也没明白

跳到报错源码分析 route 可知，串台了：ae67888

2024-12-20 04:02 UTC, luojiyin1987 commented
```bash
 ● Main business logic › should update an award

    expect(received).toMatchObject(expected)

    - Expected  - 42
    + Received  +  3

      Object {
        "createdAt": "2024-12-20T04:01:31.000Z",
        "deletedAt": null,
        "description": "Updated award description",
    -   "hackathon": Object {
    -     "autoApprove": true,
    -     "banners": Array [
    -       Object {
    -         "description": "banner image",
    -         "name": "banner",
    -         "uri": "https://github.com/git-hacker.png",
    -       },
    -     ],
    -     "createdAt": "2024-12-20T04:01:29.000Z",
    -     "detail": "<h1>Test Hackathon</h1><p>Example</p>",
    -     "displayName": "Test Hackathon",
    -     "enrollment": 0,
    -     "enrollmentEndedAt": "2024-12-21",
    -     "enrollmentStartedAt": "2024-12-20",
    -     "eventEndedAt": "2024-12-21",
    -     "eventStartedAt": "2024-12-20",
    -     "id": 1,
    -     "judgeEndedAt": "2024-12-21",
    -     "judgeStartedAt": "2024-12-20",
    -     "location": "https://github.com/git-hacker",
    -     "maxEnrollment": null,
    -     "name": "test-hackathon",
    -     "readOnly": false,
    -     "ribbon": "Test",
    -     "status": "planning",
    -     "summary": "Test Hackathon",
    -     "tags": Array [
    -       "test",
    -       "example",
    -     ],
    -     "updatedAt": "2024-12-20T04:01:29.000Z",
    -   },
    -   "id": 1,
    +   "id": 2,
        "name": "Updated Award Name",
    -   "pictures": Array [
    -     Object {
    -       "description": "Award trophy image",
    -       "name": "award-image",
    -       "uri": "https://example.com/award.png",
    -     },
    -   ],
    +   "pictures": null,
        "quantity": 2,
    -   "target": "team",
    +   "target": null,
        "updatedAt": Any<String>,
      }

      394 |         );
      395 |
    > 396 |         expect(award).toMatchObject({
          |                       ^
      397 |             ...testAward,
      398 |             ...updateData,
      399 |             updatedAt: expect.any(String)

      at Object.<anonymous> (test/main.test.ts:396:23)
```

这个测试报错还没解决

2024-12-20 09:39 UTC, TechQuery commented
> ```bash
>  ● Main business logic › should update an award
> 
>     expect(received).toMatchObject(expected)
> 
>     - Expected  - 42
>     + Received  +  3
> 
>       Object {
>         "createdAt": "2024-12-20T04:01:31.000Z",
>         "deletedAt": null,
>         "description": "Updated award description",
>     -   "hackathon": Object {
>     -     "autoApprove": true,
>     -     "banners": Array [
>     -       Object {
>     -         "description": "banner image",
>     -         "name": "banner",
>     -         "uri": "https://github.com/git-hacker.png",
>     -       },
>     -     ],
>     -     "createdAt": "2024-12-20T04:01:29.000Z",
>     -     "detail": "<h1>Test Hackathon</h1><p>Example</p>",
>     -     "displayName": "Test Hackathon",
>     -     "enrollment": 0,
>     -     "enrollmentEndedAt": "2024-12-21",
>     -     "enrollmentStartedAt": "2024-12-20",
>     -     "eventEndedAt": "2024-12-21",
>     -     "eventStartedAt": "2024-12-20",
>     -     "id": 1,
>     -     "judgeEndedAt": "2024-12-21",
>     -     "judgeStartedAt": "2024-12-20",
>     -     "location": "https://github.com/git-hacker",
>     -     "maxEnrollment": null,
>     -     "name": "test-hackathon",
>     -     "readOnly": false,
>     -     "ribbon": "Test",
>     -     "status": "planning",
>     -     "summary": "Test Hackathon",
>     -     "tags": Array [
>     -       "test",
>     -       "example",
>     -     ],
>     -     "updatedAt": "2024-12-20T04:01:29.000Z",
>     -   },
>     -   "id": 1,
>     +   "id": 2,
>         "name": "Updated Award Name",
>     -   "pictures": Array [
>     -     Object {
>     -       "description": "Award trophy image",
>     -       "name": "award-image",
>     -       "uri": "https://example.com/award.png",
>     -     },
>     -   ],
>     +   "pictures": null,
>         "quantity": 2,
>     -   "target": "team",
>     +   "target": null,
>         "updatedAt": Any<String>,
>       }
> 
>       394 |         );
>       395 |
>     > 396 |         expect(award).toMatchObject({
>           |                       ^
>       397 |             ...testAward,
>       398 |             ...updateData,
>       399 |             updatedAt: expect.any(String)
> 
>       at Object.<anonymous> (test/main.test.ts:396:23)
> ```
> 
> 这个测试报错还没解决

这就是你这个 PR 需要自己解决的了。

2024-12-21 08:22 UTC, TechQuery approved these changes

2024-12-21 08:22 UTC, merged